# Zadanie 6 (19.01.2025)
Korzystając ze zbioru Gutenberga pobrać po trzy książki Aleksandra Dumasa oraz Jane Austen i wykonać model tematyczny LDA: wyszukać po 2 tematy zarówno w książkach Verne’a jak i Austen i zwizualizować je, a następnie połączyć oba zbiory i jeszcze raz wykonać tę analizę. Sprawdzić jaki efekt da rozdzielenie na 3 tematy (w przypadku scalonego zbioru). Policzyć koherencję.

import requests

# Predefined bilingual books (title, English URL, French URL)
dumas_books = [ 
("black_tulip", "https://www.gutenberg.org/ebooks/965.txt.utf-8"),
("vicomte", "https://www.gutenberg.org/ebooks/2609.txt.utf-8"),
("marquise", "https://www.gutenberg.org/ebooks/2758.txt.utf-8")
]

austin_books = [
("letters_egypt", "https://www.gutenberg.org/ebooks/17816.txt.utf-8"),
("outpost", "https://www.gutenberg.org/ebooks/4676.txt.utf-8"),
("sailor_brothers", "https://www.gutenberg.org/ebooks/69815.txt.utf-8")
]

# Download function
def download_books(books, prefix):
    for title, url in books:
        print(f"Downloading: {title}")
        
        # Download English version
        content = requests.get(url).text
        with open(f"books/{prefix}/{prefix}_{title}.txt", "w", encoding="utf-8") as file:
            file.write(content)
        
        print(f"Downloaded {title}!")
# Run the download
download_books(dumas_books, 'dumas')
download_books(austin_books, 'austin')

In [1]:
import tmtoolkit as tm

corp = tm.corpus.Corpus.from_folder('books/austin', language="en", load_features=[])

mat, doc_labels, vocab = tm.corpus.dtm(corp, return_doc_labels=True, return_vocab=True)

In [2]:
d1 = "If you want to cause a commotion in any psychology department or any other place where animal and human behaviour is studied, all that you have to do is to claim that your dog loves you. Skeptics, critics, and even some ardent supporters will pour out into the halls to argue the pros and cons of that statement. Among the skeptics you will find the veterinarian Fred Metzge, of Pennsylvania State University, who claims that dogs probably don't feel love in the typical way humans do. Dogs make  investments in human beings because it works for them. They have something to gain from putting so-called emotions out there.  Metzger believes that dogs 'love' us only as long as we continue to reward their behaviours with treats and attention. For most dog owners, however, there is little doubt that dogs can truly love people."

d2 = "Emotions guide our lives in a million ways. Whether we're inclined to hide and avoid or ponder and express them, most of us don't realize the extent to which they are driving our thoughts and behavior. Exploring our emotions is a worthy endeavor for anyone hoping to know and develop themselves, build healthy relationships, and pursue what they want in life. Recent research has even suggested that emotional intelligence is more important than IQ, showing that it 'predicts over 54% of the variation in success' in relationships, health, and quality of life. Our emotions can offer us clues into who we are as well as how we've been affected by our history. Many of our actions are initiated by emotion, which leads to the natural question of what emotions are being surfaced and why."

d3 = "Curiosity is part of human nature. One of the first questions children learn to ask is 'why?' As adults, we continue to wonder. Using empirical methods, psychologists apply that universal curiosity to collect and interpret research data to better understand and solve some of society's most challenging problems. It's difficult, if not impossible, to think of a facet of life where psychology is not involved. Psychologists employ the scientific method - stating the question, offering a theory and then constructing rigorous laboratory or field experiments to test the hypothesis. Psychologists apply the understanding gleaned through research to create evidence-based strategies that solve problems and improve lives."

d4 = "Olga, a 22-year-old woman in Saratov, Russia took her dog and her baby son Vadim to a park and met up with friends. After a few drinks, Olga went home and left her baby behind! Luckily, her dog Lada was with the baby. Olga woke the next morning and realized the child was missing. She thought Vadim had been abducted, but her father went to the park and found the baby in his pram, with Lada still beside him. The rottweiler had stood guard over him all night long. Vadim was wet and hungry, but unharmed, and was placed in the care of his grandmother."

In [3]:
import tmtoolkit as tm

text = [d1, d2, d3, d4]
corp = tm.corpus.Corpus(dict(zip(range(len(text)), text)), language = "en")

tm.corpus.filter_clean_tokens(corp)
tm.corpus.to_lowercase(corp)
tm.corpus.lemmatize(corp)

mat, doc_labels, vocab = tm.corpus.dtm(corp, return_doc_labels=True, return_vocab=True, as_table=True)
display(mat)

,22,54,Dogs,Fred,IQ,Lada,Metzge,Metzger,Olga,Pennsylvania,...,wake,want,way,well,wet,woman,wonder,work,worthy,year
0,0,0,1,1,0,0,1,1,0,1,...,0,1,1,0,0,0,0,1,0,0
1,0,1,0,0,1,0,0,0,0,0,...,0,1,1,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
3,1,0,0,0,0,2,0,0,3,0,...,1,0,0,0,1,1,0,0,0,1

In [ ]:
from tmtoolkit.topicmod.tm_lda import compute_models_parallel

lda_params = {
    'n_topics':  2,
    'n_iter': 3,
}

models = compute_models_parallel(mat, constant_parameters=lda_params, n_max_processes=1)